In [2]:
import numpy as np
from numpy import linalg
import matplotlib.pyplot as plt

## Задача №1

#### Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [53]:
def np_arange():
    some_num = int(input('Введите число: '))
    x = np.arange(some_num)
    y = reversed(x)
    print(list(y))
np_arange()

Введите число: 9
[8, 7, 6, 5, 4, 3, 2, 1, 0]


## Задача №2

#### Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [52]:
def diag_matrix():
    some_num = int(input('Число строк: '))
    step = int(input('Шагов: '))
    x = np.diag(np.arange(some_num, 0, -step))
    print(x)   
    print('Сумма элементов диагонали: ', np.trace(x))
diag_matrix()

Число строк: 3
Шагов: 1
[[3 0 0]
 [0 2 0]
 [0 0 1]]
Сумма элементов диагонали:  6


## Задача №3

#### Решите систему уравнений:
4x + 2y + z = 4
        x + 3y = 12
        5y + 4z = -3

In [54]:
def lin_alg():
    array_a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]]) ## левая часть
    array_b = np.array([4, 12, -3]) ## правая часть
    print(linalg.solve(array_a, array_b))
lin_alg()

[ 0.46666667  3.84444444 -5.55555556]


## Задача №4

 #### найти косинусное сходство с users_stats

In [21]:
users_stats = np.array(
        [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
    np.int32)

In [22]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [159]:
def cosine(a, b):
    '''
    Расчёт косинуса угла
    для косинусной близости векторов
    ''' 
    a_len = np.linalg.norm(a)
    b_len = np.linalg.norm(b)
    return np.dot(a, b) / (a_len * b_len)

for i, user in enumerate(users_stats):
    cos = cosine(user, next_user_stats)
    result_dict = dict()
    result_dict[i] = float(cos)
    final_dict = dict([max(result_dict.items(), key=lambda k_v: k_v[1])])
#     print(result_dict)
    print(final_dict)

{0: 0.19999999999999996}
{1: 0.8451542547285165}
{2: 0.3999999999999999}
{3: 0.7905694150420948}
{4: 0.3999999999999999}
{5: 0.0}
{6: 0.0}
{7: 0.9486832980505138}
{8: 0.0}
{9: 0.0}
