In [50]:
import numpy as np
from numpy import linalg
import matplotlib.pyplot as plt

## Задача №1

#### Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [53]:
def np_arange():
    some_num = int(input('Введите число: '))
    x = np.arange(some_num)
    y = reversed(x)
    print(list(y))
np_arange()

Введите число: 9
[8, 7, 6, 5, 4, 3, 2, 1, 0]


## Задача №2

#### Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [52]:
def diag_matrix():
    some_num = int(input('Число строк: '))
    step = int(input('Шагов: '))
    x = np.diag(np.arange(some_num, 0, -step))
    print(x)   
    print('Сумма элементов диагонали: ', np.trace(x))
diag_matrix()

Число строк: 3
Шагов: 1
[[3 0 0]
 [0 2 0]
 [0 0 1]]
Сумма элементов диагонали:  6


## Задача №3

#### Решите систему уравнений:
4x + 2y + z = 4
        x + 3y = 12
        5y + 4z = -3

In [54]:
def lin_alg():
    array_a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]]) ## левая часть
    array_b = np.array([4, 12, -3]) ## правая часть
    print(linalg.solve(array_a, array_b))
lin_alg()

[ 0.46666667  3.84444444 -5.55555556]


## Задача №4

 #### найти косинусное сходство с users_stats

In [82]:
users_stats = np.array(
        [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
    np.int32)

In [83]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [69]:
# users_stats = users_stats.transpose()
# users_stats

array([[2, 1, 0, 0, 0, 0],
       [1, 1, 2, 1, 0, 0],
       [2, 0, 1, 0, 0, 0],
       [1, 1, 2, 1, 0, 1],
       [0, 0, 1, 2, 0, 0],
       [0, 0, 0, 0, 0, 5],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 3],
       [1, 0, 0, 2, 1, 4]])

In [70]:
# for user in users_stats:
#     print(user)

[2 1 0 0 0 0]
[1 1 2 1 0 0]
[2 0 1 0 0 0]
[1 1 2 1 0 1]
[0 0 1 2 0 0]
[0 0 0 0 0 5]
[1 0 0 0 0 0]
[0 1 1 0 0 0]
[0 0 0 1 1 3]
[1 0 0 2 1 4]


In [73]:
# users_stats_len = len(users_stats)
# users_stats_len

10

In [81]:
# n = 1
# some_dict = dict()
# some_list = list()

# while n <= users_stats_len:
#     for user in users_stats:
#         for num_us in user:
#             some_dict[user(n)] = some_list.append(num_us)
#         n += 1
# some_dict   

TypeError: 'numpy.ndarray' object is not callable

In [84]:
user_1 = np.array([2, 1, 0, 0, 0, 0])
user_2 = np.array([1, 1, 2, 1, 0, 0])
user_3 = np.array([2, 0, 1, 0, 0, 0])
user_4 = np.array([1, 1, 2, 1, 0, 1])
user_5 = np.array([0, 0, 1, 2, 0, 0])
user_6 = np.array([0, 0, 0, 0, 0, 5])
user_7 = np.array([1, 0, 0, 0, 0, 0])
user_8 = np.array([0, 1, 1, 0, 0, 0])
user_9 = np.array([0, 0, 0, 1, 1, 3])
user_10 = np.array([1, 0, 0, 2, 1, 4])

In [85]:
def cosine (a, b):
    a_len = np.linalg.norm(a)
    b_len = np.linalg.norm(b)
    return np.dot(a, b) / (a_len * b_len)
cosine(user_9, user_4)
# a = np.arccos(cosine(user_9, user_4)) * 360 / 2 / np.pi
# a

0.42640143271122083